let wholeNote = new Image();
wholeNote.src = "images/whole_note.svg";
let wholeRest = new Image();
wholeRest.src = "images/whole_rest.svg"
let halfNote = new Image();
halfNote.src = "images/half_note.svg";
let halfRest = new Image();
halfRest.src = "images/half_rest.svg";
let quarterNote = new Image();
quarterNote.src = "images/quarter_note.svg";
let quarterRest = new Image();
quarterRest.src = "images/quarter_rest.svg";
let eighthNote = new Image();
eighthNote.src = "images/eighth_note.svg";
let sixteenthNote = new Image();
sixteenthNote.src = "images/sixteenth_note.svg";
